# Sumarizando colunas em Python
Como obter contagem e totais com Pandas.

Referências: 
* [How to calculate summary statistics?](https://pandas.pydata.org/pandas-docs/stable/getting_started/intro_tutorials/06_calculate_statistics.html)
* [10 minutes to Pandas](https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html#viewing-data)
* [pandas.DataFrame.sort_values()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sort_values.html#pandas.DataFrame.sort_values)

#### Importante
Para o correto processamento do arquivo CSV devem ser feitas algumas modificações direto no arquivo antes de abrir pelo Python.

O arquivo desve ser mudado deste formato:
```csv
Data,Descrição,Valor,Banco,Categoria,Dia da semana
01/10/2020,Magic Dolar,"29,50",Neon,Casa,quinta-feira
01/10/2020,Distribuidora Primavera,"92,98",Neon,Lazer,quinta-feira
01/10/2020,Casa da esfiha,"19,75",Neon,Lanche,quinta-feira
05/10/2020,Grife das capas,"20,00",Neon,Reparos,segunda-feira
05/10/2020,Speed up,"326,87",Neon,Aprendizado,segunda-feira
```

Para este:
```csv
Data;Descrição;Valor;Banco;Categoria;Dia da semana
01/10/2020;Magic Dolar;29.50;Neon;Casa;quinta-feira
01/10/2020;Distribuidora Primavera;92.98;Neon;Lazer;quinta-feira
01/10/2020;Casa da esfiha;19.75;Neon;Lanche;quinta-feira
05/10/2020;Grife das capas;20.00;Neon;Reparos;segunda-feira
05/10/2020;Speed up;326.87;Neon;Aprendizado;segunda-feira
05/10/2020;Sanepar;139.99;BB;Casa;segunda-feira
```

Principais mudanças:
* O separador de colunas foi de vírgula para ponto-e-vírgula.
* Os números foram convertidos para o formato americano, com o ponto no lugar da vírgula e removidos os separadores de milhares.
* Também foram removidas as aspas duplas dos números.

In [4]:
import pandas as pd
csv = pd.read_csv('./desp-out-2020-2.csv', sep=';')
## Mostrando alguns valores
csv.head(100)

,Data,Descrição,Valor,Banco,Categoria,Dia da semana
0,01/10/2020,Magic Dolar,29.50,Neon,Casa,quinta-feira
1,01/10/2020,Distribuidora Primavera,92.98,Neon,Lazer,quinta-feira
2,01/10/2020,Casa da esfiha,19.75,Neon,Lanche,quinta-feira
3,05/10/2020,Grife das capas,20.00,Neon,Reparos,segunda-feira
4,05/10/2020,Speed up,326.87,Neon,Aprendizado,segunda-feira
5,05/10/2020,Sanepar,139.99,BB,Casa,segunda-feira
6,07/10/2020,Auto Escola Liderança,1520.00,BB,Habilitação,quarta-feira
7,09/10/2020,Pagamento do aluguel,1300.00,BB,Casa,sexta-feira
8,09/10/2020,Musitech: cordas para guitarra,45.00,BB,Instrumentos,sexta-feira
9,09/10/2020,Empório Pet,84.00,BB,Pets,sexta-feira
10,09/10/2020,Musitech: cordas para violão,29.00,Neon,Instrumentos,sexta-feira
11,09/10/2020,Posto de gasolina - Gasolina JR,50.00,Neon,Contribuição,sexta-feira
12,09/10/2020,Pestiscaria Vadeco,101.90,BB,Lanche,sexta-feira
13,10/10/2020,Pernambucanas,29.99,BB,Vestuário,sábado
14,13/10/2020,Supermercado - lanches para viagem cachoeira,31.94,BB,Lazer,terça-feira
15,13/10/2020,Sorveteria,25.65,BB,Lazer,terça-feira
16,13/10/2020,Conserta Smart conserto celular,100.00,BB,Reparos,terça-feira
17,13/10/2020,Seguro residencial,48.30,BB,Casa,terça-feira
18,15/10/2020,Hering - presente Lucas,59.99,BB,Presentes,quinta-feira
19,15/10/2020,Santa Pizza,67.00,BB,Lanche,quinta-feira
20,15/10/2020,Pagamento conta luz,148.45,BB,Casa,quinta-feira
21,15/10/2020,Pagamento internet casa,149.90,BB,Casa,quinta-feira
22,15/10/2020,Pagamento internet pais,89.90,BB,Contribuição,quinta-feira
23,15/10/2020,Cabo de carregador do celular,25.00,Dinheiro,Reparos,quinta-feira
24,16/10/2020,Pagamento conserto da guitarra,370.00,BB,Reparos,sexta-feira
25,18/10/2020,Sorveteria Ki Delicia,44.00,BB,Lazer,domingo
26,18/10/2020,Dízimo 1ª parte,380.00,BB,Contribuição,domingo
27,18/10/2020,Açaí Wave,32.00,BB,Lanche,domingo
28,20/10/2020,Pagamento fatura cartão,436.31,BB,Crédito,terça-feira
29,19/10/2020,Café da manhã Londrina,11.00,Neon,Lanche,segunda-feira
30,19/10/2020,Havan,214.84,Neon,Casa,segunda-feira
31,19/10/2020,Almoço Londrina,61.20,Neon,Lanche,segunda-feira
32,19/10/2020,Lanche shopping Londrina,14.00,Neon,Lanche,segunda-feira
33,19/10/2020,Gasolina Londrina,30.00,Neon,Contribuição,segunda-feira
34,20/10/2020,Pagamento fatura cartão,369.99,Neon,Crédito,terça-feira
35,21/10/2020,Cheque compensado - cartão supermercado,501.71,BB,Crédito,quarta-feira
36,22/10/2020,Aquarela - pasta coral Jessica,14.50,BB,Presentes,quinta-feira
37,22/10/2020,Safari - Banho Bruce,35.00,BB,Pets,quinta-feira
38,22/10/2020,Açaí Wave,87.00,BB,Lanche,quinta-feira
39,23/10/2020,Saque para viagem,50.00,BB,Viagem,sexta-feira
40,24/10/2020,Gasolina,77.31,BB,Viagem,sábado
41,24/10/2020,Café da manhã Londrina,33.75,BB,Viagem,sábado
42,24/10/2020,Pagamento supermercado Paraná,100.51,BB,Viagem,sábado
43,25/10/2020,Gasolina,86.00,BB,Viagem,domingo
44,26/10/2020,Pagamento TIM,51.99,BB,Telefonia,segunda-feira
45,26/10/2020,Tarifa,13.25,BB,Taxas,segunda-feira
46,29/10/2020,Casa da esfiha,22.25,Neon,Lanche,quinta-feira
47,31/10/2020,Cachaçaria,152.00,Neon,Lazer,sábado

In [6]:
## Vendo a estrutura dos objetos
print('Informação estrutural:\n\n')
csv.info()

Informação estrutural:


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Data           48 non-null     object
 1   Descrição      48 non-null     object
 2   Valor          48 non-null     float64
 3   Banco          48 non-null     object
 4   Categoria      48 non-null     object
 5   Dia da semana  48 non-null     object
dtypes: float64(1), object(5)
memory usage: 2.4+ KB

In [11]:
# Média por dia da semana
lst = csv.groupby('Dia da semana').count()
print(lst)

               Data  Descrição  Valor  Banco  Categoria
Dia da semana
domingo           4          4      4      4          4
quarta-feira      2          2      2      2          2
quinta-feira     13         13     13     13         13
segunda-feira    10         10     10     10         10
sexta-feira       8          8      8      8          8
sábado            5          5      5      5          5
terça-feira       6          6      6      6          6

In [13]:
lst = csv.groupby('Dia da semana')['Valor'].mean()
print(lst)

Dia da semana
domingo           135.500000
quarta-feira     1010.855000
quinta-feira       64.709231
segunda-feira      88.314000
sexta-feira       253.737500
sábado             78.712000
terça-feira       168.698333
Name: Valor, dtype: float64

In [17]:
# Contagem por categoria
lst = csv.groupby('Categoria')['Valor'].count()
lst.head(50)

Categoria
Aprendizado     1
Casa            7
Contribuição    4
Crédito         3
Habilitação     1
Instrumentos    2
Lanche          9
Lazer           5
Pets            2
Presentes       2
Reparos         4
Taxas           1
Telefonia       1
Vestuário       1
Viagem          5
Name: Valor, dtype: int64

In [19]:
lst = csv.groupby('Categoria')['Valor'].sum()
lst.head(50)

Categoria
Aprendizado      326.87
Casa            2030.98
Contribuição     549.90
Crédito         1308.01
Habilitação     1520.00
Instrumentos      74.00
Lanche           416.10
Lazer            346.57
Pets             119.00
Presentes         74.49
Reparos          515.00
Taxas             13.25
Telefonia         51.99
Vestuário         29.99
Viagem           347.57
Name: Valor, dtype: float64

In [23]:
# Ordenando os resultados
# Primeiro transforma em um DataFrame para poder usar funções do Pandas
lst2 = pd.DataFrame(lst)
# Ascendente
lst2.sort_values(by='Valor')

                Valor
Categoria
Taxas           13.25
Vestuário       29.99
Telefonia       51.99
Instrumentos    74.00
Presentes       74.49
Pets           119.00
Aprendizado    326.87
Lazer          346.57
Viagem         347.57
Lanche         416.10
Reparos        515.00
Contribuição   549.90
Crédito       1308.01
Habilitação   1520.00
Casa          2030.98

In [26]:
# Sort reverso (descendente)
lst2.sort_values(by='Valor', ascending=False)

                Valor
Categoria
Casa          2030.98
Habilitação   1520.00
Crédito       1308.01
Contribuição   549.90
Reparos        515.00
Lanche         416.10
Viagem         347.57
Lazer          346.57
Aprendizado    326.87
Pets           119.00
Presentes       74.49
Instrumentos    74.00
Telefonia       51.99
Vestuário       29.99
Taxas           13.25